// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6MewnUMqoL--zXmOIaBG-Tg0uAoLL-HQ',
    appId: '1:517182293428:web:ae1e83e81d53133e26dee1',
    messagingSenderId: '517182293428',
    projectId: 'gudangpd-commerce',
    authDomain: 'gudangpd-commerce.firebaseapp.com',
    databaseURL: 'https://gudangpd-commerce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gudangpd-commerce.firebasestorage.app',
    measurementId: 'G-D18KKS56ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUgJLK0CXEfw8HyKG71sb4modFCHhq6L0',
    appId: '1:517182293428:android:d6c6e624a9209d9a26dee1',
    messagingSenderId: '517182293428',
    projectId: 'gudangpd-commerce',
    databaseURL: 'https://gudangpd-commerce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gudangpd-commerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV5WwtRE1yn0Y9CZ_k8TLjKpLR4I-VvI4',
    appId: '1:517182293428:ios:6f80a39ee061a25e26dee1',
    messagingSenderId: '517182293428',
    projectId: 'gudangpd-commerce',
    databaseURL: 'https://gudangpd-commerce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gudangpd-commerce.firebasestorage.app',
    iosBundleId: 'com.example.gudangpdAdmin',
  );
}
